global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: chat-monolith
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["tasks.chat-monolith_app"]
        type: A
        port: 9091

  - job_name: chat-monolith-postgres
    dns_sd_configs:
      - names: ["tasks.chat-monolith_postgres-exporter"]
        type: A
        port: 9187

  - job_name: chat-monolith-node
    dns_sd_configs:
      - names: ["tasks.chat-monolith_node-exporter"]
        type: A
        port: 9100

  - job_name: chat-monolith-cadvisor
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["tasks.chat-monolith_cadvisor"]
        type: A
        port: 8080